services:
  - type: web
    name: titech-moodle
    env: docker
    plan: starter
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: titech-moodle-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: titech-moodle-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: titech-moodle-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: titech-moodle-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: titech-moodle-db
          property: port
      - key: WWWROOT
        fromService:
          name: titech-moodle
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    disk:
      name: moodledata
      mountPath: /var/www/moodledata

databases:
  - name: titech-moodle-db
    plan: free
    databaseName: moodle
    user: moodle
